spring:
  application:
    name: gateway-server

server:
  port: 8768

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int(10000,19999)}
    statusPageUrl: http://${spring.cloud.client.ipAddress}:${server.port}${server.context-path}/swagger
  client:
    registerWithEureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  ignoredServices: "*"
  # 下面的这个属性在boot版本1.4以上和cloud的版本Camden版本必须有，否则cookie带不到下游
  sensitiveHeaders: "*"
  routes:
    bs-dreamport-user: /dreamport-user/**

hystrix:
  command:
    # Globally config
    default:
      execution:
        # Disable Hystrix timeout globally (for all services)
        timeout.enabled: true
        # Set Hystrix timeout to 60s globally
        isolation.thread.timeoutInMilliseconds: 600000
  threadpool:
    default:
      coreSize: 2000
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 200

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 10000
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false

endpoints:
  restart:
    enabled: false
  shutdown:
    enabled: false
  health:
    sensitive: true